// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// p1d
NumericVector p1d(NumericVector ee, NumericVector ff, IntegerVector delta, NumericMatrix Z);
RcppExport SEXP _BA23001021_p1d(SEXP eeSEXP, SEXP ffSEXP, SEXP deltaSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ee(eeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ff(ffSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(p1d(ee, ff, delta, Z));
    return rcpp_result_gen;
END_RCPP
}
// p2d
NumericMatrix p2d(NumericVector ee, NumericVector ff, IntegerVector delta, NumericMatrix Z);
RcppExport SEXP _BA23001021_p2d(SEXP eeSEXP, SEXP ffSEXP, SEXP deltaSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ee(eeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ff(ffSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(p2d(ee, ff, delta, Z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BA23001021_p1d", (DL_FUNC) &_BA23001021_p1d, 4},
    {"_BA23001021_p2d", (DL_FUNC) &_BA23001021_p2d, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_BA23001021(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
