# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

p1d <- function(ee, ff, delta, Z) {
    .Call('_BA23001021_p1d', PACKAGE = 'BA23001021', ee, ff, delta, Z)
}

p2d <- function(ee, ff, delta, Z) {
    .Call('_BA23001021_p2d', PACKAGE = 'BA23001021', ee, ff, delta, Z)
}

